MONGODB_HOST: mongodb-{{ env }}.sudhakar.shop.shop
REDIS_HOST: redis-{{ env }}.sudhakar.shop.shop
MYSQL_HOST: mysql-{{ env }}.sudhakar.shop.shop 
RABBITMQ_HOST: rabbitmq-{{ env }}.sudhakar.shop.shop 
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.sudhakar.shop.shop
USER_HOST: user.backend-alb-{{ env }}.sudhakar.shop.shop
CART_HOST: cart.backend-alb-{{ env }}.sudhakar.shop.shop
SHIPPING_HOST: shipping.backend-alb-{{ env }}.sudhakar.shop.shop
PAYMENT_HOST: payment.backend-alb-{{ env }}.sudhakar.shop.shop
